# fly.toml app configuration file generated for quickslice on 2025-10-29T21:49:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quickslice'
primary_region = 'sjc'

[build]
  image = 'ghcr.io/bigmoves/quickslice:sha-370076b'

[env]
  HOST = '0.0.0.0'
  PORT = '8080'
  DATABASE_URL = '/data/quickslice.db'
  EXTERNAL_BASE_URL = 'https://quickslice.fly.dev'
  ADMIN_DIDS = 'did:plc:bcgltzqazw5tb6k2g3ttenbj'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[mounts]]
  source = 'app_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
